export interface Room {
  id: string;
  name: string;
  abbreviation?: string;
  type: string;
  lecturerNames?: string[];
  navigationNodeId?: string;
  x: number;
  y: number;
}

export const rooms: Room[] = [
  {
    id: 'entrance',
    name: 'Department Entrance',
    type: 'Entrance',
    navigationNodeId: 'entrance-door',
    x: 57,
    y: 97,
  },
  {
    id: 'hod',
    name: 'Head of Computer Science',
    abbreviation: 'HD, CS',
    type: 'Office',
    navigationNodeId: 'hod-door',
    x: 12,
    y: 17,
  },
  {
    id: 'secretary',
    name: "Secretary's Office",
    type: 'Office',
    navigationNodeId: 'secretary-door',
    x: 12,
    y: 27,
  },
  {
    id: 'messenger',
    name: "Messenger's Office",
    type: 'Office',
    navigationNodeId: 'messenger-door',
    x: 12,
    y: 35,
  },
  {
    id: 'electrical-services',
    name: 'Electrical Services',
    abbreviation: 'Es',
    type: 'Services',
    navigationNodeId: 'electrical-services-door',
    x: 9,
    y: 7,
  },
  {
    id: 'lab-1',
    name: 'Computer Lab 1',
    abbreviation: 'CL1',
    type: 'Laboratory',
    navigationNodeId: 'lab-1-door',
    x: 53,
    y: 22,
  },
  {
    id: 'lab-2',
    name: 'Computer Lab 2',
    abbreviation: 'CL2',
    type: 'Laboratory',
    navigationNodeId: 'lab-2-door',
    x: 53,
    y: 42,
  },
  {
    id: 'lab-3',
    name: 'Computer Lab 3',
    abbreviation: 'CL3',
    type: 'Laboratory',
    navigationNodeId: 'lab-3-door',
    x: 53,
    y: 62,
  },
  {
    id: 'cs-r2',
    name: 'Computer Studies Room 2',
    abbreviation: 'CS, R2',
    type: 'Classroom',
    lecturerNames: ['Dr E. Lampi', 'Mr Mofya Phiri'],
    navigationNodeId: 'cs-r2-door',
    x: 12,
    y: 37,
  },
  {
    id: 'cs-r3',
    name: 'Computer Studies Room 3',
    abbreviation: 'CS, R3',
    type: 'Classroom',
    lecturerNames: ['Mr A. Theu', 'Mr M. Phiri'],
    navigationNodeId: 'cs-r3-door',
    x: 12,
    y: 47,
  },
  {
    id: 'cs-r4',
    name: 'Computer Studies Room 4',
    abbreviation: 'CS, R4',
    type: 'Classroom',
    lecturerNames: ['Mr D. Zulu'],
    navigationNodeId: 'cs-r4-door',
    x: 12,
    y: 57,
  },
  {
    id: 'cs-r5',
    name: 'Computer Studies Room 5',
    abbreviation: 'CS, R5',
    type: 'Classroom',
    lecturerNames: ['Prof J. Phiri'],
    navigationNodeId: 'cs-r5-door',
    x: 12,
    y: 67,
  },
  {
    id: 'cs-r6',
    name: 'Computer Studies Room 6',
    abbreviation: 'CS, R6',
    type: 'Classroom',
    lecturerNames: ['Mrs Monica M. Kabemba'],
    navigationNodeId: 'cs-r6-door',
    x: 12,
    y: 77,
  },
  {
    id: 'staff-only',
    name: 'Staff Only',
    type: 'Restricted Area',
    navigationNodeId: 'staff-only-door',
    x: 12,
    y: 88,
  },
  {
    id: 'ladies',
    name: "Ladies' Toilet",
    type: 'Restroom',
    navigationNodeId: 'ladies-door',
    x: 7,
    y: 10,
  },
  {
    id: 'visitors-toilet',
    name: 'Students and Visitors Toilet',
    abbreviation: 'V and Stu.',
    type: 'Restroom',
    navigationNodeId: 'visitors-toilet-door',
    x: 73,
    y: 88,
  },
  {
    id: 'seminar',
    name: 'Seminar Room',
    type: 'Seminar',
    navigationNodeId: 'seminar-door',
    x: 62,
    y: 87,
  },
  {
    id: 'hardware-lab',
    name: 'Hardware Lab',
    type: 'Laboratory',
    navigationNodeId: 'hardware-lab-door',
    x: 91,
    y: 89,
  },
];
